Compiled from "Exception.scala"
public final class scala.util.control.Exception extends java.lang.Object
  SourceFile: "Exception.scala"
  ScalaSig: length = 0x3
   05 00 00 
  RuntimeVisibleAnnotations: length = 0xB
   00 01 00 4E 00 01 00 4F 73 00 50 
  InnerClass: 
   public By=class scala/util/control/Exception$By of class scala/util/control/Exception
   public Try=class scala/util/control/Exception$Try of class scala/util/control/Exception
   public Catch=class scala/util/control/Exception$Catch of class scala/util/control/Exception
   public final $anon$4=class scala/util/control/Exception$$anon$4 of class scala/util/control/Exception
   public final $anon$5=class scala/util/control/Exception$$anon$5 of class scala/util/control/Exception
   public final $anon$3=class scala/util/control/Exception$$anon$3 of class scala/util/control/Exception
   public final $anon$1=class scala/util/control/Exception$$anon$1 of class scala/util/control/Exception
   public Finally=class scala/util/control/Exception$Finally of class scala/util/control/Exception
   public abstract Described=class scala/util/control/Exception$Described of class scala/util/control/Exception
   public abstract Described$class=class scala/util/control/Exception$Described$class of class scala/util/control/Exception
   public final $anonfun$failing$1=class scala/util/control/Exception$$anonfun$failing$1 of class scala/util/control/Exception
   public final $anonfun$handling$1=class scala/util/control/Exception$$anonfun$handling$1 of class scala/util/control/Exception
   public final $anonfun$ignoring$1=class scala/util/control/Exception$$anonfun$ignoring$1 of class scala/util/control/Exception
   public final $anonfun$catching$1=class scala/util/control/Exception$$anonfun$catching$1 of class scala/util/control/Exception
   public final $anonfun$allCatch$1=class scala/util/control/Exception$$anonfun$allCatch$1 of class scala/util/control/Exception
   public final $anonfun$unwrapping$1=class scala/util/control/Exception$$anonfun$unwrapping$1 of class scala/util/control/Exception
   public final $anonfun$scala$util$control$Exception$$wouldMatch$1=class scala/util/control/Exception$$anonfun$scala$util$control$Exception$$wouldMatch$1 of class scala/util/control/Exception
  minor version: 0
  major version: 49
  Constant pool:
Asciz	SourceFile;
Asciz	Exception.scala;
Asciz	unwrap$1;
Asciz	(Ljava/lang/Throwable;Lscala/collection/Seq;)Ljava/lang/Throwable;;
Asciz	Code;
Asciz	scala/util/control/Exception$;
class	scala/util/control/Exception$
Asciz	MODULE$;
Asciz	Lscala/util/control/Exception$;;
NameAndType	MODULE$:Lscala/util/control/Exception$;
Field	scala/util/control/Exception$.MODULE$:Lscala/util/control/Exception$;
NameAndType	unwrap$1:(Ljava/lang/Throwable;Lscala/collection/Seq;)Ljava/lang/Throwable;
Method	scala/util/control/Exception$.unwrap$1:(Ljava/lang/Throwable;Lscala/collection/Seq;)Ljava/lang/Throwable;
Asciz	fun$1;
Asciz	(Lscala/Function1;Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;;
NameAndType	fun$1:(Lscala/Function1;Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
Method	scala/util/control/Exception$.fun$1:(Lscala/Function1;Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
Asciz	scala$util$control$Exception$$wouldMatch;
Asciz	(Ljava/lang/Throwable;Lscala/collection/Seq;)Z;
NameAndType	scala$util$control$Exception$$wouldMatch:(Ljava/lang/Throwable;Lscala/collection/Seq;)Z
Method	scala/util/control/Exception$.scala$util$control$Exception$$wouldMatch:(Ljava/lang/Throwable;Lscala/collection/Seq;)Z
Asciz	unwrapping;
Asciz	(Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;;
NameAndType	unwrapping:(Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
Method	scala/util/control/Exception$.unwrapping:(Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
Asciz	<T:Ljava/lang/Object;>(Lscala/collection/Seq<Ljava/lang/Class<*>;>;)Lscala/util/control/Exception$Catch<TT;>;;
Asciz	Signature;
Asciz	saving;
Asciz	(Ljava/lang/Object;Ljava/lang/Object;Lscala/Function1;)Lscala/util/control/Exception$Catch;;
NameAndType	saving:(Ljava/lang/Object;Ljava/lang/Object;Lscala/Function1;)Lscala/util/control/Exception$Catch;
Method	scala/util/control/Exception$.saving:(Ljava/lang/Object;Ljava/lang/Object;Lscala/Function1;)Lscala/util/control/Exception$Catch;
Asciz	<A:Ljava/lang/Object;>(TA;TA;Lscala/Function1<TA;Ljava/lang/Object;>;)Lscala/util/control/Exception$Catch<Lscala/runtime/Nothing$;>;;
Asciz	ultimately;
Asciz	(Lscala/Function0;)Lscala/util/control/Exception$Catch;;
NameAndType	ultimately:(Lscala/Function0;)Lscala/util/control/Exception$Catch;
Method	scala/util/control/Exception$.ultimately:(Lscala/Function0;)Lscala/util/control/Exception$Catch;
Asciz	<T:Ljava/lang/Object;>(Lscala/Function0<Ljava/lang/Object;>;)Lscala/util/control/Exception$Catch<TT;>;;
Asciz	handling;
Asciz	(Lscala/collection/Seq;)Lscala/util/control/Exception$By;;
NameAndType	handling:(Lscala/collection/Seq;)Lscala/util/control/Exception$By;
Method	scala/util/control/Exception$.handling:(Lscala/collection/Seq;)Lscala/util/control/Exception$By;
Asciz	<T:Ljava/lang/Object;>(Lscala/collection/Seq<Ljava/lang/Class<*>;>;)Lscala/util/control/Exception$By<Lscala/Function1<Ljava/lang/Throwable;TT;>;Lscala/util/control/Exception$Catch<TT;>;>;;
Asciz	failing;
NameAndType	failing:(Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
Method	scala/util/control/Exception$.failing:(Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
Asciz	<T:Ljava/lang/Object;>(Lscala/collection/Seq<Ljava/lang/Class<*>;>;)Lscala/util/control/Exception$Catch<Lscala/Option<TT;>;>;;
Asciz	ignoring;
NameAndType	ignoring:(Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
Method	scala/util/control/Exception$.ignoring:(Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
Asciz	(Lscala/collection/Seq<Ljava/lang/Class<*>;>;)Lscala/util/control/Exception$Catch<Ljava/lang/Object;>;;
Asciz	catching;
Asciz	(Lscala/PartialFunction;)Lscala/util/control/Exception$Catch;;
NameAndType	catching:(Lscala/PartialFunction;)Lscala/util/control/Exception$Catch;
Method	scala/util/control/Exception$.catching:(Lscala/PartialFunction;)Lscala/util/control/Exception$Catch;
Asciz	<T:Ljava/lang/Object;>(Lscala/PartialFunction<Ljava/lang/Throwable;TT;>;)Lscala/util/control/Exception$Catch<TT;>;;
NameAndType	catching:(Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
Method	scala/util/control/Exception$.catching:(Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
Asciz	noCatch;
Asciz	()Lscala/util/control/Exception$Catch;;
NameAndType	noCatch:()Lscala/util/control/Exception$Catch;
Method	scala/util/control/Exception$.noCatch:()Lscala/util/control/Exception$Catch;
Asciz	()Lscala/util/control/Exception$Catch<Lscala/runtime/Nothing$;>;;
Asciz	allCatch;
NameAndType	allCatch:()Lscala/util/control/Exception$Catch;
Method	scala/util/control/Exception$.allCatch:()Lscala/util/control/Exception$Catch;
Asciz	<T:Ljava/lang/Object;>()Lscala/util/control/Exception$Catch<TT;>;;
Asciz	nothingCatcher;
Asciz	()Lscala/PartialFunction;;
NameAndType	nothingCatcher:()Lscala/PartialFunction;
Method	scala/util/control/Exception$.nothingCatcher:()Lscala/PartialFunction;
Asciz	()Lscala/PartialFunction<Ljava/lang/Throwable;Lscala/runtime/Nothing$;>;;
Asciz	fromExceptionCatcher;
Asciz	(Lscala/PartialFunction;)Lscala/PartialFunction;;
NameAndType	fromExceptionCatcher:(Lscala/PartialFunction;)Lscala/PartialFunction;
Method	scala/util/control/Exception$.fromExceptionCatcher:(Lscala/PartialFunction;)Lscala/PartialFunction;
Asciz	<T:Ljava/lang/Object;>(Lscala/PartialFunction<Ljava/lang/Exception;TT;>;)Lscala/PartialFunction<Ljava/lang/Throwable;TT;>;;
Asciz	ScalaSig;
Asciz	Lscala/reflect/ScalaSignature;;
Asciz	bytes;
Asciz	\ruw!BI!C#yGH/[8o\tA!Ad_:$(o71B;uS2TaBgG.Y!\tQ1\"D\r!a!\"Ai!!C#yGH/[8o'\rYaB\tQi#I\tA\1oO*\t1#kCZBAy%M[3diBqG\r%D'G.Y(cUGCA$=S:LGO!ad \r^2iKJ,\"I\t]\t3eLEqU1si&GNR;oGRLwN\tI1r!!\nJS\"A!BAs_>$h(C\tYc!AqC\mZ3\n5r#!+ie><M7f\tYc1c1A\t%)AQ\"N])Bqu5j]\"a\ne2!aA!os!1h=A)pY3qi&|gnQ1uG\",'/>B!q#\t A!\t!s(\r]A'\tei\"\t\"bg!)1iC\t!bM]8nbW\r;j_:\r^2iKJ,\"!R%ScA$6\t11A!GC1CLA*qMBqI%9[A%A=R3tGJL'-35saCR!+%S:LG\n'BqV+A!8ji\"9q+b#A8b[,!\t5vs!aF.\nq3A)sK,g-_?\n11:j]T!\tl!C1)qZ3tG\"91-a\n!!C0eKNwJ3r)\tV\rCgE\tA-a$iK!W?,7o\t)lE-\t,7oY6#\t!\\to&$R3tGRan\\")oa3\t1Cs3/u_N#(/8h)!CAv\tqCx\t!y1N\1mYfBAz-Aq)\twZ\t*Ay!!m3z!\r9RpU}2z]lWM7Y$\taCA)\t!!3BB> \tAXm\nICA+!bBAmI^]lW\r\t#1HAA\n\r\tg\t)=A1}yG[3s\tYBC%1N<pW4a!a\"!B\"biDWBA[R!!sZA1bSAIA(U\tv\tYE1[!BMA\t%)A\tEQBB%FaDA;)!C]a4j]V\t/m1A{1!AB(qi&|gCBu!!Q\ne4j]BbGA\tYQ\t\nI%ai\"a\t-1*!AQGA\"\tIC;!\t!a\t5AA%9Qb\n#\tIu!u!\tI&!mAA8s+\ti&a\t}\tu\r\ta\rDaCA3/\"\t!bO!V\tW9CA6/\r!!A4'H;CA-;!\t!!\tMk\nYEH;\t9E1s\"1\"!p\tQ1h!AqCA8\t) uAAAA\t7z+\t)a\"\t\taEaCA3{\"\t!bOBb_A?\t1\t/u)\tuAAAI)\tg$j]dG.\n\nC|#\t?\t]QC31a9u+\tY*!)\tu1\t/mq\taFaCA3+#\t!bOBb_AK\tQ\t/uy\n*uAAAV)5feV!QVA\)\ty+!/\r]\t\tlIA[\r\tL&$.:A\n9BfF!ACC>(\r!a/\t]iQ\ti\"BIq/;iBH._I\rF-#B$cJQQMA_\t)A\t5QaA\t/E7%a2\nMgAAGk:G/[8oc!Aq[A\t\tI.u_>H/[8o+\t\tYEH;\tiEw\tYbuAAAr!!x.R5uQXCAAs!9QDAt!9W,11^[1:z+\ty/a>\t%hBw%(!S\nMB~k2MA|\t%C\n1C|%(Q1AuaB2biDWM]RaRAkD1Baj\n\t! A1-;dQS$\taB)IAaA)q)!;v\"A1P!\t|\nAA !\ty(!;\tEACAA{!\ty(!;\tUQB7!BA! AGa$1C!QD\tk<\"CA'!\tB!9RP!\t]CK!\"Aa\n]\tY$!>\t]CW)BA!4Q!!qB!91B!\r$1KI\"AiC\t%B18A!q# B!\tI+!;\tmBCB!9Wv\"AVAu\t\t%D\t%CB#baFAYG\tcJYQ\rB \t)B%\t9Bai{\nB)S$\tAaQ08tiG-V\tmCB,;RaRAu32\rB.\t-\t)Ga\rA!\t]!q\nCA\t}B~3B\"!j!1MKYh\t5#B$j\n%clYQ\rB1\t)BY%\ra_BaRj!AqRAu\t\n\tUCAc\"\t?\tII\"zQ\tC~-\r\" qan;iS:<7);dQXCBA!9e\t\t\t5)AqB\8uQ&twmQ1uG\",'\t[AQBF!\tG\\"biDWBG#RaRA2\rBI\t%$qC1C.\r\"9an\\"biDWCBM!9Q\t\tu5)A3B\8DCR\tC[ABR!\r^2iS:<WBSW#BAa*.B)q)!*BGa+Iy\n\"ABX?\rA!-D8-9uS>t7Eg9,C6!:faG/3?aIL!1iYLa0\n\tuvLADY8E1$!Ba1 \tQ!4\ryF%\rC[ABd+IMa4\t\t-'\tu!Q\ta\t=G!F\tQ14!N!2A\tU!A2\tk\"Q3\ABn!IwM\8sS:<GBo?BaRA'\"A!qBl\tEg\rf\n%#.<\ncjQ!1Bl\t)A}##Cp.!\tA!=\5oOV!!1B~))P!@iBa>]\tYD!?AYB3[$\t!bg!A!qBwyEg\t\r\r#.<cQ1Bw\t)A}#3G-1qf,ba!\ru1BBYA1\"!4\t\t!A9q#!5\rmcI!ga\ra\r\ta\ruAACB!\t!bg\t\t!C!\taa\t\t\r2q\t-1qCB!\tim!\tA\rUCB!\ta!\tLHBB_Ab!\r*1qCq\"91QG\r]5b]dN\4\t\re2\tw)EHida\r]\t\tnIB !\r4\t\ne\rMB!ACMRaRAABa,41q\t\t/\tM6\nyE[wiE1\"!b!4\tQ!4\ryF+ZAAB,))H^5nCR,G._3y\\r#B$\ruc`I!ga\ra\rwMC1})gCO\naa]1wS:<WBB5c\"B!'l\rU4\t[1p1q3WC22MB9\t)ha\ra\r\"A1qOB2y'oK^4\r\tw1~11/;uKJbaFAi_bBBA11Qk:<(/9qS:<WBBC#Baa\"B)q)!\nBga#Iy\"ABX\raa$]l!%1\t\rM5q\t5\nm6Q\ta\r]EACBM\"\t!Bg\tqJ\t\ru5\" Qqo\;mI6Go5\r\r6qUBU!\r921UK3!a\"p_2,McY\n1$!Yka'A\r5aB2mCNXm\t_)l!/\rE&bABZ\rQ1m7mK$n8\n\t\r]6'BB^RAB^{2MB`\t)\tma'\ta\r?2bBBc%1qYa4%o\7Fq,^5p]N$Ba!3PJ)11Y1QZBb\t\tABe1a$/4j]lWM;?!yka1A\rE#B4MBBk3RAB^/2MBm\t)Yna1\ta\r?:;
Asciz	RuntimeVisibleAnnotations;
Asciz	InnerClasses;
Asciz	scala/util/control/Exception$By;
class	scala/util/control/Exception$By
Asciz	scala/util/control/Exception;
class	scala/util/control/Exception
Asciz	By;
Asciz	scala/util/control/Exception$Try;
class	scala/util/control/Exception$Try
Asciz	Try;
Asciz	scala/util/control/Exception$Catch;
class	scala/util/control/Exception$Catch
Asciz	Catch;
Asciz	scala/util/control/Exception$$anon$4;
class	scala/util/control/Exception$$anon$4
Asciz	$anon$4;
Asciz	scala/util/control/Exception$$anon$5;
class	scala/util/control/Exception$$anon$5
Asciz	$anon$5;
Asciz	scala/util/control/Exception$$anon$3;
class	scala/util/control/Exception$$anon$3
Asciz	$anon$3;
Asciz	scala/util/control/Exception$$anon$1;
class	scala/util/control/Exception$$anon$1
Asciz	$anon$1;
Asciz	scala/util/control/Exception$Finally;
class	scala/util/control/Exception$Finally
Asciz	Finally;
Asciz	scala/util/control/Exception$Described;
class	scala/util/control/Exception$Described
Asciz	Described;
Asciz	scala/util/control/Exception$Described$class;
class	scala/util/control/Exception$Described$class
Asciz	Described$class;
Asciz	scala/util/control/Exception$$anonfun$failing$1;
class	scala/util/control/Exception$$anonfun$failing$1
Asciz	$anonfun$failing$1;
Asciz	scala/util/control/Exception$$anonfun$handling$1;
class	scala/util/control/Exception$$anonfun$handling$1
Asciz	$anonfun$handling$1;
Asciz	scala/util/control/Exception$$anonfun$ignoring$1;
class	scala/util/control/Exception$$anonfun$ignoring$1
Asciz	$anonfun$ignoring$1;
Asciz	scala/util/control/Exception$$anonfun$catching$1;
class	scala/util/control/Exception$$anonfun$catching$1
Asciz	$anonfun$catching$1;
Asciz	scala/util/control/Exception$$anonfun$allCatch$1;
class	scala/util/control/Exception$$anonfun$allCatch$1
Asciz	$anonfun$allCatch$1;
Asciz	scala/util/control/Exception$$anonfun$unwrapping$1;
class	scala/util/control/Exception$$anonfun$unwrapping$1
Asciz	$anonfun$unwrapping$1;
Asciz	scala/util/control/Exception$$anonfun$scala$util$control$Exception$$wouldMatch$1;
class	scala/util/control/Exception$$anonfun$scala$util$control$Exception$$wouldMatch$1
Asciz	$anonfun$scala$util$control$Exception$$wouldMatch$1;
Asciz	java/lang/Object;
class	java/lang/Object

{
public static final java.lang.Throwable unwrap$1(java.lang.Throwable, scala.collection.Seq);
  Signature: (Ljava/lang/Throwable;Lscala/collection/Seq;)Ljava/lang/Throwable;
  Code:
   Stack=3, Locals=2, Args_size=2
	getstatic	Field scala/util/control/Exception$.MODULE$:Lscala/util/control/Exception$;
	aload_0
	aload_1
	invokevirtual	Method scala/util/control/Exception$.unwrap$1:(Ljava/lang/Throwable;Lscala/collection/Seq;)Ljava/lang/Throwable;
	areturn
  Labels:

public static final scala.util.control.Exception$Catch fun$1(scala.Function1, scala.collection.Seq);
  Signature: (Lscala/Function1;Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
  Code:
   Stack=3, Locals=2, Args_size=2
	getstatic	Field scala/util/control/Exception$.MODULE$:Lscala/util/control/Exception$;
	aload_0
	aload_1
	invokevirtual	Method scala/util/control/Exception$.fun$1:(Lscala/Function1;Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
	areturn
  Labels:

public static final boolean scala$util$control$Exception$$wouldMatch(java.lang.Throwable, scala.collection.Seq);
  Signature: (Ljava/lang/Throwable;Lscala/collection/Seq;)Z
  Code:
   Stack=3, Locals=2, Args_size=2
	getstatic	Field scala/util/control/Exception$.MODULE$:Lscala/util/control/Exception$;
	aload_0
	aload_1
	invokevirtual	Method scala/util/control/Exception$.scala$util$control$Exception$$wouldMatch:(Ljava/lang/Throwable;Lscala/collection/Seq;)Z
	ireturn
  Labels:

public static final scala.util.control.Exception$Catch unwrapping(scala.collection.Seq);
  Signature: (Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
  Code:
   Stack=2, Locals=1, Args_size=1
	getstatic	Field scala/util/control/Exception$.MODULE$:Lscala/util/control/Exception$;
	aload_0
	invokevirtual	Method scala/util/control/Exception$.unwrapping:(Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
	areturn
  Labels:
  Signature: length = 0x2
   00 1A 

public static final scala.util.control.Exception$Catch saving(java.lang.Object, java.lang.Object, scala.Function1);
  Signature: (Ljava/lang/Object;Ljava/lang/Object;Lscala/Function1;)Lscala/util/control/Exception$Catch;
  Code:
   Stack=4, Locals=3, Args_size=3
	getstatic	Field scala/util/control/Exception$.MODULE$:Lscala/util/control/Exception$;
	aload_0
	aload_1
	aload_2
	invokevirtual	Method scala/util/control/Exception$.saving:(Ljava/lang/Object;Ljava/lang/Object;Lscala/Function1;)Lscala/util/control/Exception$Catch;
	areturn
  Labels:
  Signature: length = 0x2
   00 20 

public static final scala.util.control.Exception$Catch ultimately(scala.Function0);
  Signature: (Lscala/Function0;)Lscala/util/control/Exception$Catch;
  Code:
   Stack=2, Locals=1, Args_size=1
	getstatic	Field scala/util/control/Exception$.MODULE$:Lscala/util/control/Exception$;
	aload_0
	invokevirtual	Method scala/util/control/Exception$.ultimately:(Lscala/Function0;)Lscala/util/control/Exception$Catch;
	areturn
  Labels:
  Signature: length = 0x2
   00 25 

public static final scala.util.control.Exception$By handling(scala.collection.Seq);
  Signature: (Lscala/collection/Seq;)Lscala/util/control/Exception$By;
  Code:
   Stack=2, Locals=1, Args_size=1
	getstatic	Field scala/util/control/Exception$.MODULE$:Lscala/util/control/Exception$;
	aload_0
	invokevirtual	Method scala/util/control/Exception$.handling:(Lscala/collection/Seq;)Lscala/util/control/Exception$By;
	areturn
  Labels:
  Signature: length = 0x2
   00 2A 

public static final scala.util.control.Exception$Catch failing(scala.collection.Seq);
  Signature: (Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
  Code:
   Stack=2, Locals=1, Args_size=1
	getstatic	Field scala/util/control/Exception$.MODULE$:Lscala/util/control/Exception$;
	aload_0
	invokevirtual	Method scala/util/control/Exception$.failing:(Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
	areturn
  Labels:
  Signature: length = 0x2
   00 2E 

public static final scala.util.control.Exception$Catch ignoring(scala.collection.Seq);
  Signature: (Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
  Code:
   Stack=2, Locals=1, Args_size=1
	getstatic	Field scala/util/control/Exception$.MODULE$:Lscala/util/control/Exception$;
	aload_0
	invokevirtual	Method scala/util/control/Exception$.ignoring:(Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
	areturn
  Labels:
  Signature: length = 0x2
   00 32 

public static final scala.util.control.Exception$Catch catching(scala.PartialFunction);
  Signature: (Lscala/PartialFunction;)Lscala/util/control/Exception$Catch;
  Code:
   Stack=2, Locals=1, Args_size=1
	getstatic	Field scala/util/control/Exception$.MODULE$:Lscala/util/control/Exception$;
	aload_0
	invokevirtual	Method scala/util/control/Exception$.catching:(Lscala/PartialFunction;)Lscala/util/control/Exception$Catch;
	areturn
  Labels:
  Signature: length = 0x2
   00 37 

public static final scala.util.control.Exception$Catch catching(scala.collection.Seq);
  Signature: (Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
  Code:
   Stack=2, Locals=1, Args_size=1
	getstatic	Field scala/util/control/Exception$.MODULE$:Lscala/util/control/Exception$;
	aload_0
	invokevirtual	Method scala/util/control/Exception$.catching:(Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
	areturn
  Labels:
  Signature: length = 0x2
   00 1A 

public static final scala.util.control.Exception$Catch noCatch();
  Signature: ()Lscala/util/control/Exception$Catch;
  Code:
   Stack=1, Locals=0, Args_size=0
	getstatic	Field scala/util/control/Exception$.MODULE$:Lscala/util/control/Exception$;
	invokevirtual	Method scala/util/control/Exception$.noCatch:()Lscala/util/control/Exception$Catch;
	areturn
  Labels:
  Signature: length = 0x2
   00 3E 

public static final scala.util.control.Exception$Catch allCatch();
  Signature: ()Lscala/util/control/Exception$Catch;
  Code:
   Stack=1, Locals=0, Args_size=0
	getstatic	Field scala/util/control/Exception$.MODULE$:Lscala/util/control/Exception$;
	invokevirtual	Method scala/util/control/Exception$.allCatch:()Lscala/util/control/Exception$Catch;
	areturn
  Labels:
  Signature: length = 0x2
   00 42 

public static final scala.PartialFunction nothingCatcher();
  Signature: ()Lscala/PartialFunction;
  Code:
   Stack=1, Locals=0, Args_size=0
	getstatic	Field scala/util/control/Exception$.MODULE$:Lscala/util/control/Exception$;
	invokevirtual	Method scala/util/control/Exception$.nothingCatcher:()Lscala/PartialFunction;
	areturn
  Labels:
  Signature: length = 0x2
   00 47 

public static final scala.PartialFunction fromExceptionCatcher(scala.PartialFunction);
  Signature: (Lscala/PartialFunction;)Lscala/PartialFunction;
  Code:
   Stack=2, Locals=1, Args_size=1
	getstatic	Field scala/util/control/Exception$.MODULE$:Lscala/util/control/Exception$;
	aload_0
	invokevirtual	Method scala/util/control/Exception$.fromExceptionCatcher:(Lscala/PartialFunction;)Lscala/PartialFunction;
	areturn
  Labels:
  Signature: length = 0x2
   00 4C 

}

